version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: proyectonuevo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ale12345678
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8088:80"
    depends_on:
      - postgres

  springboot:
    build: .
    container_name: springboot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/proyectonuevo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ale12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 8085
    ports:
      - "8087:8085"
    depends_on:
      - postgres

volumes:
  postgres_data: